# Generated by Django 4.2.2 on 2023-07-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_city_alter_ad_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category_images/'),
            preserve_default=False,
        ),
    ]
